# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

jobs:
  - job: LinuxNode12
    pool:
     vmImage: 'Ubuntu-latest'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "12.x"
        displayName: "Install Node.js 12.x"
      - template: azure-pipelines-steps.yml

  - job: WindowsNode10
    pool:
      vmImage: vs2017-win2016
    steps:
      - script: |
          git config --global core.autocrlf false
          git config --global core.symlinks true
        displayName: 'Preserve LF endings and symbolic links on check out'
      - task: NodeTool@0
        inputs:
          versionSpec: "10.x"
        displayName: "Install Node.js 10.x"
      - template: azure-pipelines-steps.yml



