steps:
  - script: npm ci
    displayName: "npm install"

  - script: node --throw-deprecation --trace-warnings --expose-gc node_modules/jest/bin/jest --forceExit --logHeapUsage --runInBand --ci --reporters=default --reporters=jest-junit
    displayName: "Run Jest"

  - script: npx codecov -f "./coverage/coverage-final.json" -y "./.codecov.yml" -t $(CODECOV_TOKEN)
    displayName: "Upload to Codecov"

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: "**/junit.xml"

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/cobertura-coverage.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/**/coverage"
